[package]
name = "depo-api"
version = "0.3.1"
edition = "2021"
description = "API for the Blockchain Commons Depository ('depo') server."
authors = ["Blockchain Commons"]
keywords = ["cryptocurrency", "security", "key-management", "recovery", "server"]
repository = "https://github.com/BlockchainCommons/bc-depo-api-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography", "database", "security", "web-programming::http-client"]
documentation = "https://docs.rs/depo-api"

[dependencies]
dcbor = { version = "^0.13.0", features = ["multithreaded"] }
# dcbor = { path = "../dcbor", features = ["multithreaded"] }

bc-ur = "^0.3.0"
# bc-ur = { path = "../bc-ur" }

bc-envelope = { version = "^0.14.0", features = ["multithreaded"] }
# bc-envelope = { path = "../bc-envelope", features = ["multithreaded"] }

bc-components = "^0.9.0"
# bc-components = { path = "../bc-components" }

bytes = "^1.5.0"
anyhow = "^1.0.0"
hex = "^0.4.3"

[dev-dependencies]
indoc = "^2.0.4"
hex-literal = "^0.4.1"

[features]
multithreaded = ["dcbor/multithreaded", "bc-envelope/multithreaded"]
