[package]
name = "depo-api"
version = "0.1.0"
edition = "2021"

[dependencies]
dcbor = { version = "0.11.0", features = ["multithreaded"] }
# dcbor = { path = "../dcbor", features = ["multithreaded"] }

bc-ur = "0.2.2"
# bc-ur = { path = "../bc-ur" }

bc-envelope = { version = "0.12.0", features = ["multithreaded"] }
# bc-envelope = { path = "../bc-envelope", features = ["multithreaded"] }

bc-components = "0.7.0"
# bc-components = { path = "../bc-components" }

bytes = "1.5.0"
anyhow = "1.0"
hex = "0.4.3"

[dev-dependencies]
indoc = "2.0.4"
hex-literal = "0.4.1"

[features]
multithreaded = ["dcbor/multithreaded", "bc-envelope/multithreaded"]
