[package]
name = "depo-api"
version = "0.5.0"
edition = "2021"
description = "API for the Blockchain Commons Depository ('depo') server."
authors = ["Blockchain Commons"]
keywords = ["cryptocurrency", "security", "key-management", "recovery", "server"]
repository = "https://github.com/BlockchainCommons/bc-depo-api-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography", "database", "security", "web-programming::http-client"]
documentation = "https://docs.rs/depo-api"

[dependencies]
dcbor = { version = "^0.14.0", features = ["multithreaded"] }
bc-ur = "^0.4.0"
bc-envelope = { version = "^0.17.0", features = ["multithreaded"] }
bc-components = "^0.11.0"
bytes = "^1.5.0"
anyhow = "^1.0.0"
hex = "^0.4.3"

[dev-dependencies]
indoc = "^2.0.4"
hex-literal = "^0.4.1"

[features]
multithreaded = ["dcbor/multithreaded", "bc-envelope/multithreaded"]
