[package]
name = "depo-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# dcbor = "0.10.0"
dcbor = { path = "../dcbor" }

# bc-ur = "0.2.1"
bc-ur = { path = "../bc-ur" }

# bc-envelope = "0.11.0"
bc-envelope = { path = "../bc-envelope" }

# bc-components = "0.6.0"
bc-components = { path = "../bc-components" }

bytes = "1.5.0"
anyhow = "1.0"
hex = "0.4.3"

[dev-dependencies]
indoc = "2.0.4"
hex-literal = "0.4.1"
